In [1]:
import pandas as pd
import numpy as np

c:\Users\AKSHAT SHAW\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
df_3005 = pd.read_csv(r"C:/Users/AKSHAT SHAW/OneDrive - iitr.ac.in/Desktop/Spark_25_project/03005.csv")

In [3]:
df_3005.head()

,prcp(mm/day),tmax(C),tmin(C),tavg(C),srad_lw(w/m2),srad_sw(w/m2),wind_u(m/s),wind_v(m/s),wind(m/s),rel_hum(%),...,sm_lvl4(kg/m2),Soil_Moisture_Sum,Soil_Saturation,soil_awsc_max,Actual_Soil_Saturation,date,AWC,Actual_Soil_Saturation_New,station_id,soil_awc_avg
0,0.00,28.00,13.21,20.60,340.89,250.87,1.58,1.51,2.19,48.39,...,531.81,786.30,784.76,150,5.231733,01-01-1980,0.196154,4000.731109,3005,0.196154
1,0.07,28.06,14.49,21.28,357.40,238.01,0.85,0.34,0.92,55.88,...,531.75,785.85,784.65,150,5.231000,02-01-1980,0.196154,4000.170325,3005,0.196154
2,0.45,27.19,13.63,20.41,362.47,202.55,-0.35,-1.36,1.40,57.16,...,531.70,785.48,784.92,150,5.232800,03-01-1980,0.196154,4001.546794,3005,0.196154
3,0.72,26.27,13.38,19.82,366.46,173.07,-2.01,-0.60,2.10,80.77,...,531.66,785.66,784.98,150,5.233200,04-01-1980,0.196154,4001.852676,3005,0.196154
4,3.11,23.99,14.17,19.08,377.85,119.04,-1.01,-1.73,2.00,84.53,...,531.63,787.46,789.50,150,5.263333,05-01-1980,0.196154,4024.895777,3005,0.196154

In [4]:
df_base = pd.read_csv(r"C:/Users/AKSHAT SHAW/OneDrive - iitr.ac.in/Desktop/Spark_25_project/baseflow_all_basins.csv")

In [5]:
df_base.head()

,date,3002,3005,3008,3013,3018,3019,3020,3029,3030,...,15024,15026,15030,15032,17003,17006,17011,17019,17022,10013
0,1980-01-01,NaN,23.200000,36.100000,NaN,30.700000,NaN,12.80,15.1,NaN,...,NaN,50.900000,4.800000,116.0,2.2,3.800000,462.200000,23.700000,10.300000,NaN
1,1980-01-02,NaN,22.000000,35.781102,NaN,31.012728,NaN,12.30,15.3,NaN,...,NaN,49.049024,4.500000,112.8,2.1,3.500000,458.210089,24.000000,8.638803,NaN
2,1980-01-03,NaN,21.400000,35.465957,NaN,30.000000,NaN,11.10,14.6,NaN,...,NaN,47.262349,4.477016,112.6,2.1,3.100000,454.313717,25.965158,5.800000,NaN
3,1980-01-04,NaN,21.384851,35.155992,NaN,29.800000,NaN,9.70,14.3,NaN,...,NaN,45.562745,4.400000,106.5,2.0,3.096050,445.800000,28.128636,4.737067,NaN
4,1980-01-05,NaN,21.369522,34.850262,NaN,29.200000,NaN,8.67,14.0,NaN,...,NaN,43.923668,4.200000,106.3,2.0,3.092284,439.600000,30.505124,3.938515,NaN

## Taking on the baseflow values from here:

In [6]:
df_base = df_base[['date', '3005']]

In [7]:
df_base.head()

         date       3005
0  1980-01-01  23.200000
1  1980-01-02  22.000000
2  1980-01-03  21.400000
3  1980-01-04  21.384851
4  1980-01-05  21.369522

In [8]:
df_3005['date'] = pd.to_datetime(df_3005['date'], format='mixed', dayfirst=True, errors='coerce')
df_base['date'] = pd.to_datetime(df_base['date'], format='mixed', dayfirst=True, errors='coerce')

In [9]:
# Merge two DataFrames on a single column
merged_df = pd.merge(df_3005, df_base, on='date', how='inner')

In [10]:
merged_df.head()

,prcp(mm/day),tmax(C),tmin(C),tavg(C),srad_lw(w/m2),srad_sw(w/m2),wind_u(m/s),wind_v(m/s),wind(m/s),rel_hum(%),...,Soil_Moisture_Sum,Soil_Saturation,soil_awsc_max,Actual_Soil_Saturation,date,AWC,Actual_Soil_Saturation_New,station_id,soil_awc_avg,3005
0,0.00,28.00,13.21,20.60,340.89,250.87,1.58,1.51,2.19,48.39,...,786.30,784.76,150,5.231733,1980-01-01,0.196154,4000.731109,3005,0.196154,23.200000
1,0.07,28.06,14.49,21.28,357.40,238.01,0.85,0.34,0.92,55.88,...,785.85,784.65,150,5.231000,1980-01-02,0.196154,4000.170325,3005,0.196154,22.000000
2,0.45,27.19,13.63,20.41,362.47,202.55,-0.35,-1.36,1.40,57.16,...,785.48,784.92,150,5.232800,1980-01-03,0.196154,4001.546794,3005,0.196154,21.400000
3,0.72,26.27,13.38,19.82,366.46,173.07,-2.01,-0.60,2.10,80.77,...,785.66,784.98,150,5.233200,1980-01-04,0.196154,4001.852676,3005,0.196154,21.384851
4,3.11,23.99,14.17,19.08,377.85,119.04,-1.01,-1.73,2.00,84.53,...,787.46,789.50,150,5.263333,1980-01-05,0.196154,4024.895777,3005,0.196154,21.369522

In [11]:
len(df_3005), len(df_base), len(merged_df)

(14976, 14555, 14555)

## Loading the static variables

In [12]:
merged_df.columns

Index(['prcp(mm/day)', 'tmax(C)', 'tmin(C)', 'tavg(C)', 'srad_lw(w/m2)',
       'srad_sw(w/m2)', 'wind_u(m/s)', 'wind_v(m/s)', 'wind(m/s)',
       'rel_hum(%)', 'pet(mm/day)', 'pet_gleam(mm/day)', 'aet_gleam(mm/day)',
       'evap_canopy(kg/m2/s)', 'evap_surface(kg/m2/s)', 'sm_lvl1(kg/m2)',
       'sm_lvl2(kg/m2)', 'sm_lvl3(kg/m2)', 'sm_lvl4(kg/m2)',
       'Soil_Moisture_Sum', 'Soil_Saturation', 'soil_awsc_max',
       'Actual_Soil_Saturation', 'date', 'AWC', 'Actual_Soil_Saturation_New',
       'station_id', 'soil_awc_avg', '3005'],
      dtype='object')

In [ ]:
merged_df.dropna(inplace=True)
merged_df.drop(columns=['date', 'station_id'], inplace = True)

In [ ]:
# merged_df.to_csv("merged_df_3005.csv", index=False)

In [2]:
import pandas as pd
merged_df = pd.read_csv("merged_df_3005.csv")

c:\Users\AKSHAT SHAW\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [3]:
df_static = pd.read_csv("static_3005.csv").drop("gauge_id", axis=1)

In [4]:
row = df_static.loc[0]
n = len(merged_df)
duplicates = pd.DataFrame([row] * n, index=merged_df.index)

In [5]:
merged_df = pd.concat([merged_df, duplicates], axis=1)
cat = merged_df.select_dtypes(include=['object', 'string']).columns
cat

Index(['high_prec_timing', 'low_prec_timing', 'geol_class_1st',
       'geol_class_2nd', 'dom_land_cover', 'ghi_stn_id', 'cwc_site_name',
       'river_basin', 'cwc_river', 'ghi_group', 'hsg_major'],
      dtype='object')

In [6]:
from sklearn.preprocessing import OrdinalEncoder

label_encoders = {}

for column in cat:
    le = OrdinalEncoder()
    # Reshape to 2D
    reshaped = merged_df[[column]]  # Same as merged_df[column].values.reshape(-1, 1)
    merged_df[column] = le.fit_transform(reshaped)
    label_encoders[column] = le

In [7]:
import torch 
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [8]:
s = len(merged_df)

In [9]:
from torch.utils.data import Dataset, DataLoader, TensorDataset

X = merged_df.drop('3005', axis=1) 
y = merged_df['3005']

X_train = X[:round(s*0.8)]
y_train = y[:round(s*0.8)]

X_test = X[round(s*0.9):]
y_test = y[round(s*0.9):]

X_val = X[round(s*0.8):round(s*0.9)]
y_val = y[round(s*0.8):round(s*0.9)]


scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
X_val = scaler.transform(X_val)

In [10]:
X_test.shape, y_test.shape

((1389, 220), (1389,))

In [11]:
# X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
# X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
# y_train_tensor = torch.from_numpy(y_train.to_numpy().astype(np.float32))
# y_test_tensor = torch.from_numpy(y_test.to_numpy().astype(np.float32))

In [12]:
class CustomDataset(Dataset):
  def __init__(self, features, labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return len(self.features)

  def __getitem__(self, idx):
    return self.features[idx], self.labels[idx]
  
class SequenceDataset(Dataset):
    def __init__(self, features, labels, sequence_length = 20):
        """
        features: shape (N, num_features)
        labels: shape (N,) or (N, 1)
        sequence_length: number of time steps in each input sequence
        """
        self.sequence_length = sequence_length

        self.features = torch.tensor(features, dtype=torch.float32)
        self.labels = torch.tensor(labels.to_numpy(), dtype=torch.float32)

        # Ensure labels have shape (N, 1)
        if self.labels.ndim == 1:
            self.labels = self.labels.unsqueeze(1)

    def __len__(self):
        return len(self.features) - self.sequence_length

    def __getitem__(self, idx):
        x = self.features[idx : idx + self.sequence_length]  # shape: (seq_len, num_features)
        y = self.labels[idx + self.sequence_length]          # target: next step
        return x, y

In [13]:
train_dataset = SequenceDataset(X_train, y_train)
test_dataset = SequenceDataset(X_test, y_test)
val_dataset = SequenceDataset(X_val, y_val)

train_loader = DataLoader(
                    train_dataset,
                    batch_size=32,
                    shuffle=True)

test_loader = DataLoader(
                    test_dataset,
                    batch_size=32,
                    shuffle=True)
val_loader = DataLoader(
                    val_dataset,
                    batch_size=32,
                    shuffle=True
)

In [14]:
# # Map static features to initial hidden and cell state
# self.static_to_h = nn.Linear(static_size, hidden_size * num_layers)
# self.static_to_c = nn.Linear(static_size, hidden_size * num_layers)

# # Map static -> (batch_size, hidden_size * num_layers)
# h0 = self.static_to_h(x_static).view(self.num_layers, batch_size, self.hidden_size)
# c0 = self.static_to_c(x_static).view(self.num_layers, batch_size, self.hidden_size)
        
import torch.nn as nn

class LSTMModel(nn.Module):
    def __init__(self, input_size, num_layers):
        super().__init__()

        self.lstm1 = nn.LSTM(input_size, 256, num_layers, batch_first=True)
        self.dropout1 = nn.Dropout(0.5)
        self.relu1 = nn.ReLU()

        self.lstm2 = nn.LSTM(256, 128, num_layers, batch_first=True)
        self.dropout2 = nn.Dropout(0.5)
        self.relu2 = nn.ReLU()

        self.lstm3 = nn.LSTM(128, 32, num_layers, batch_first=True)
        self.dropout3 = nn.Dropout(0.5)
        self.relu3 = nn.ReLU()

        self.fc = nn.Linear(32, 1)

    def forward(self, x):
        out, _ = self.lstm1(x)
        out = self.dropout1(out)
        out = self.relu1(out)

        out, _ = self.lstm2(out)
        out = self.dropout2(out)
        out = self.relu2(out)

        out, _ = self.lstm3(out)
        out = self.dropout3(out)
        out = self.relu3(out)

        out = out[:, -1, :]  # Last time step
        out = self.fc(out)
        return out

In [15]:
num_features = X_train.shape[1]
model = LSTMModel(input_size=num_features, num_layers=1)
model.to("cuda")

LSTMModel(
  (lstm1): LSTM(220, 256, batch_first=True)
  (dropout1): Dropout(p=0.5, inplace=False)
  (relu1): ReLU()
  (lstm2): LSTM(256, 128, batch_first=True)
  (dropout2): Dropout(p=0.5, inplace=False)
  (relu2): ReLU()
  (lstm3): LSTM(128, 32, batch_first=True)
  (dropout3): Dropout(p=0.5, inplace=False)
  (relu3): ReLU()
  (fc): Linear(in_features=32, out_features=1, bias=True)
)

In [16]:
import wandb
wandb.login()

wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.
wandb: Currently logged in as: akshatshaw47 (akshatshaw47-iit-roorkee). Use `wandb login --relogin` to force relogin

True

In [17]:

wandb.init(project="spark'25-lstm-testing", 
    name = 'test3',
    config={
    "epochs": 1000,
    "batch_size": 64,
    "lr": 0.0001,
    "optimizer": "Adam",
    "loss_fn": "MSELoss",
    "model": "LSTM"
})

In [18]:
class LogRMSELoss(nn.Module):
    def __init__(self, eps=1e-6):
        super().__init__()
        self.eps = eps  # to avoid log(0)

    def forward(self, pred, target):
        # Clamp values to avoid log(0)
        pred = torch.clamp(pred, min=self.eps)
        target = torch.clamp(target, min=self.eps)

        # Compute log RMSE
        log_pred = torch.log(pred)
        log_target = torch.log(target)
        loss = torch.sqrt(torch.mean((log_pred - log_target) ** 2))
        return loss

In [19]:
# criterion = nn.MSELoss()
criterion = LogRMSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.0001)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# Training loop with validation
for epoch in range(1000):
    model.train()
    train_loss = 0.0
    for xb, yb in train_loader:
        xb, yb = xb.to(device), yb.to(device)
        pred = model(xb)
        loss = criterion(pred, yb)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        train_loss += loss.item()

    # Validation
    model.eval()
    val_loss = 0.0
    with torch.no_grad():
        for xb, yb in val_loader:
            xb, yb = xb.to(device), yb.to(device)
            pred = model(xb)
            loss = criterion(pred, yb)
            val_loss += loss.item()

    train_loss /= len(train_loader)
    val_loss /= len(val_loader)

    print(f"Epoch {epoch+1}, Train Loss: {train_loss:.4f}, Val Loss: {val_loss:.4f}")
    wandb.log({"epoch": epoch+1, "train_loss": train_loss, "val_loss": val_loss})

Epoch 1, Train Loss: 6.8546, Val Loss: 3.2792
Epoch 2, Train Loss: 3.0306, Val Loss: 2.6012
Epoch 3, Train Loss: 2.6766, Val Loss: 2.4457
Epoch 4, Train Loss: 2.5244, Val Loss: 2.3500
Epoch 5, Train Loss: 2.4293, Val Loss: 2.2792
Epoch 6, Train Loss: 2.3718, Val Loss: 2.2215
Epoch 7, Train Loss: 2.3143, Val Loss: 2.1644
Epoch 8, Train Loss: 2.2571, Val Loss: 2.1142
Epoch 9, Train Loss: 2.1916, Val Loss: 2.0604
Epoch 10, Train Loss: 2.1497, Val Loss: 2.0120
Epoch 11, Train Loss: 2.1116, Val Loss: 1.9696
Epoch 12, Train Loss: 2.0508, Val Loss: 1.9264
Epoch 13, Train Loss: 2.0179, Val Loss: 1.8824
Epoch 14, Train Loss: 1.9636, Val Loss: 1.8406
Epoch 15, Train Loss: 1.9198, Val Loss: 1.8022
Epoch 16, Train Loss: 1.8827, Val Loss: 1.7635
Epoch 17, Train Loss: 1.8512, Val Loss: 1.7281
Epoch 18, Train Loss: 1.8155, Val Loss: 1.6889
Epoch 19, Train Loss: 1.7731, Val Loss: 1.6578
Epoch 20, Train Loss: 1.7421, Val Loss: 1.6277
Epoch 21, Train Loss: 1.7071, Val Loss: 1.6002
Epoch 22, Train Loss: 1.6671, Val Loss: 1.5732
Epoch 23, Train Loss: 1.6594, Val Loss: 1.5447
Epoch 24, Train Loss: 1.6138, Val Loss: 1.5184
Epoch 25, Train Loss: 1.5859, Val Loss: 1.4955
Epoch 26, Train Loss: 1.5652, Val Loss: 1.4715
Epoch 27, Train Loss: 1.5425, Val Loss: 1.4513
Epoch 28, Train Loss: 1.5180, Val Loss: 1.4359
Epoch 29, Train Loss: 1.4973, Val Loss: 1.4159
Epoch 30, Train Loss: 1.4811, Val Loss: 1.3997
Epoch 31, Train Loss: 1.4584, Val Loss: 1.3812
Epoch 32, Train Loss: 1.4406, Val Loss: 1.3721
Epoch 33, Train Loss: 1.4310, Val Loss: 1.3589
Epoch 34, Train Loss: 1.4162, Val Loss: 1.3448
Epoch 35, Train Loss: 1.4012, Val Loss: 1.3354
Epoch 36, Train Loss: 1.3859, Val Loss: 1.3275
Epoch 37, Train Loss: 1.3741, Val Loss: 1.3199
Epoch 38, Train Loss: 1.3647, Val Loss: 1.3113
Epoch 39, Train Loss: 1.2644, Val Loss: 1.1050
Epoch 40, Train Loss: 1.1841, Val Loss: 1.1301
Epoch 41, Train Loss: 1.1430, Val Loss: 1.0707
Epoch 42, Train Loss: 1.0923, Val Loss: 1.0914
Epoch 43, Train Loss: 1.0411, Val Loss: 1.1117
Epoch 44, Train Loss: 1.0007, Val Loss: 1.0919
Epoch 45, Train Loss: 0.9853, Val Loss: 1.0712
Epoch 46, Train Loss: 0.9444, Val Loss: 1.0364
Epoch 47, Train Loss: 0.9178, Val Loss: 1.0720
Epoch 48, Train Loss: 0.8958, Val Loss: 1.0725
Epoch 49, Train Loss: 0.8698, Val Loss: 1.0289
Epoch 50, Train Loss: 0.8614, Val Loss: 1.0567
Epoch 51, Train Loss: 0.8366, Val Loss: 1.0352
Epoch 52, Train Loss: 0.8157, Val Loss: 1.0104
Epoch 53, Train Loss: 0.8136, Val Loss: 1.0476
Epoch 54, Train Loss: 0.7784, Val Loss: 1.0299
Epoch 55, Train Loss: 0.7585, Val Loss: 1.0052
Epoch 56, Train Loss: 0.7452, Val Loss: 1.0016
Epoch 57, Train Loss: 0.7408, Val Loss: 1.0045
Epoch 58, Train Loss: 0.7259, Val Loss: 0.9965
Epoch 59, Train Loss: 0.6992, Val Loss: 1.0139
Epoch 60, Train Loss: 0.6854, Val Loss: 0.9602
Epoch 61, Train Loss: 0.6856, Val Loss: 0.9872
Epoch 62, Train Loss: 0.6665, Val Loss: 0.9747
Epoch 63, Train Loss: 0.6589, Val Loss: 1.0084
Epoch 64, Train Loss: 0.6494, Val Loss: 0.9500
Epoch 65, Train Loss: 0.6315, Val Loss: 0.9736
Epoch 66, Train Loss: 0.6287, Val Loss: 0.9575
Epoch 67, Train Loss: 0.6608, Val Loss: 0.9783
Epoch 68, Train Loss: 0.6180, Val Loss: 0.9601
Epoch 69, Train Loss: 0.5971, Val Loss: 0.9690
Epoch 70, Train Loss: 0.5910, Val Loss: 0.9443
Epoch 71, Train Loss: 0.5850, Val Loss: 0.9486
Epoch 72, Train Loss: 0.5694, Val Loss: 0.9421
Epoch 73, Train Loss: 0.5700, Val Loss: 0.9539
Epoch 74, Train Loss: 0.5716, Val Loss: 0.9507
Epoch 75, Train Loss: 0.5481, Val Loss: 0.9104
Epoch 76, Train Loss: 0.5404, Val Loss: 0.8784
Epoch 77, Train Loss: 0.5358, Val Loss: 0.8918
Epoch 78, Train Loss: 0.5291, Val Loss: 0.8927
Epoch 79, Train Loss: 0.5223, Val Loss: 0.9175
Epoch 80, Train Loss: 0.5242, Val Loss: 0.8876
Epoch 81, Train Loss: 0.5087, Val Loss: 0.8943
Epoch 82, Train Loss: 0.5208, Val Loss: 0.8853
Epoch 83, Train Loss: 0.5103, Val Loss: 0.8942
Epoch 84, Train Loss: 0.4995, Val Loss: 0.8870
Epoch 85, Train Loss: 0.4938, Val Loss: 0.8835
Epoch 86, Train Loss: 0.4883, Val Loss: 0.8991
Epoch 87, Train Loss: 0.4809, Val Loss: 0.8297
Epoch 88, Train Loss: 0.4710, Val Loss: 0.8337
Epoch 89, Train Loss: 0.4755, Val Loss: 0.8877
Epoch 90, Train Loss: 0.4727, Val Loss: 0.8144
Epoch 91, Train Loss: 0.4666, Val Loss: 0.8513
Epoch 92, Train Loss: 0.4759, Val Loss: 0.8169
Epoch 93, Train Loss: 0.4612, Val Loss: 0.8344
Epoch 94, Train Loss: 0.4592, Val Loss: 0.8579
Epoch 95, Train Loss: 0.4538, Val Loss: 0.8359
Epoch 96, Train Loss: 0.4497, Val Loss: 0.8526
Epoch 97, Train Loss: 0.4425, Val Loss: 0.8557
Epoch 98, Train Loss: 0.4430, Val Loss: 0.8824
Epoch 99, Train Loss: 0.4345, Val Loss: 0.8354
Epoch 100, Train Loss: 0.4342, Val Loss: 0.8720
Epoch 101, Train Loss: 0.4310, Val Loss: 0.8211
Epoch 102, Train Loss: 0.4268, Val Loss: 0.7883
Epoch 103, Train Loss: 0.4239, Val Loss: 0.8105
Epoch 104, Train Loss: 0.4144, Val Loss: 0.8385
Epoch 105, Train Loss: 0.4160, Val Loss: 0.8586
Epoch 106, Train Loss: 0.4180, Val Loss: 0.8587
Epoch 107, Train Loss: 0.4232, Val Loss: 0.8620
Epoch 108, Train Loss: 0.4081, Val Loss: 0.8400
Epoch 109, Train Loss: 0.4032, Val Loss: 0.8715
Epoch 110, Train Loss: 0.4081, Val Loss: 0.8489
Epoch 111, Train Loss: 0.4113, Val Loss: 0.8555
Epoch 112, Train Loss: 0.4018, Val Loss: 0.8214
Epoch 113, Train Loss: 0.3952, Val Loss: 0.8649
Epoch 114, Train Loss: 0.3942, Val Loss: 0.8517
Epoch 115, Train Loss: 0.3931, Val Loss: 0.8635
Epoch 116, Train Loss: 0.3903, Val Loss: 0.8426
Epoch 117, Train Loss: 0.3888, Val Loss: 0.8578
Epoch 118, Train Loss: 0.3928, Val Loss: 0.8426
Epoch 119, Train Loss: 0.3859, Val Loss: 0.9000
Epoch 120, Train Loss: 0.3887, Val Loss: 0.8756
Epoch 121, Train Loss: 0.3904, Val Loss: 0.8299
Epoch 122, Train Loss: 0.3917, Val Loss: 0.8867
Epoch 123, Train Loss: 0.3886, Val Loss: 0.8390
Epoch 124, Train Loss: 0.3806, Val Loss: 0.8288
Epoch 125, Train Loss: 0.3922, Val Loss: 0.8294
Epoch 126, Train Loss: 0.3888, Val Loss: 0.8494
Epoch 127, Train Loss: 0.3727, Val Loss: 0.8729
Epoch 128, Train Loss: 0.3701, Val Loss: 0.8574
Epoch 129, Train Loss: 0.3724, Val Loss: 0.8813
Epoch 130, Train Loss: 0.3695, Val Loss: 0.8785
Epoch 131, Train Loss: 0.3675, Val Loss: 0.8576
Epoch 132, Train Loss: 0.3609, Val Loss: 0.8593
Epoch 133, Train Loss: 0.3615, Val Loss: 0.8571
Epoch 134, Train Loss: 0.3567, Val Loss: 0.8684
Epoch 135, Train Loss: 0.3561, Val Loss: 0.8608
Epoch 136, Train Loss: 0.3540, Val Loss: 0.8785
Epoch 137, Train Loss: 0.3507, Val Loss: 0.8671
Epoch 138, Train Loss: 0.3565, Val Loss: 0.8765
Epoch 139, Train Loss: 0.3594, Val Loss: 0.8532
Epoch 140, Train Loss: 0.3547, Val Loss: 0.8532
Epoch 141, Train Loss: 0.3574, Val Loss: 0.8783
Epoch 142, Train Loss: 0.3573, Val Loss: 0.8557
Epoch 143, Train Loss: 0.3508, Val Loss: 0.8920
Epoch 144, Train Loss: 0.3517, Val Loss: 0.8777
Epoch 145, Train Loss: 0.3468, Val Loss: 0.8789
Epoch 146, Train Loss: 0.3378, Val Loss: 0.8898
Epoch 147, Train Loss: 0.3521, Val Loss: 0.8775
Epoch 148, Train Loss: 0.3593, Val Loss: 0.8431
Epoch 149, Train Loss: 0.3413, Val Loss: 0.8237
Epoch 150, Train Loss: 0.3410, Val Loss: 0.8706
Epoch 151, Train Loss: 0.3457, Val Loss: 0.8686
Epoch 152, Train Loss: 0.3355, Val Loss: 0.8494
Epoch 153, Train Loss: 0.3375, Val Loss: 0.8326
Epoch 154, Train Loss: 0.3433, Val Loss: 0.8390
Epoch 155, Train Loss: 0.3366, Val Loss: 0.8736
Epoch 156, Train Loss: 0.3481, Val Loss: 0.8642
Epoch 157, Train Loss: 0.3485, Val Loss: 0.8750

KeyboardInterrupt: